#!/bin/bash
jupyter serverextension enable --py nbserverproxy --sys-prefix

export DASK_TICK_MAXIMUM_DELAY=5s
export DASK_DISTRIBUTED__DIAGNOSTICS_LINK={JUPYTERHUB_SERVICE_PREFIX}proxy/{port}/status
export DASK_KUBERNETES__WORKER_TEMPLATE_PATH=${PWD}/worker-template.yaml
export DASK_KUBERNETES__WORKER_NAME=dask-{JUPYTERHUB_USER}-{uuid}

# set worker image url in worker template
if [[ -z "${JUPYTER_IMAGE_SPEC}" ]]; then
    echo "JUPYTER_IMAGE_SPEC is not set"
else
  sed -i -e "s|WORKER_IMAGE|${JUPYTER_IMAGE_SPEC}|g" ${DASK_KUBERNETES__WORKER_TEMPLATE_PATH}
fi

# Debug
env | grep JUPYTER > env_at_postBuild.txt

#EOF
